package ui;

import Interface.DotGGHoaDonDAO;
import dao.BanHangDao;
import dao.ChatLieuDao;
import dao.ChiTietHoaDonDao;
import dao.DanhSachSpDao;
import dao.DotGGHoaDonDAOIpml;
import dao.DotGiamGia_Ipml;
import dao.HoaDon2Dao;
import dao.HoaDonChoDao;
import dao.HoaDonDao;
import dao.KhachHangDao;
import dao.KhuyenMaiDao;

import dao.KichThuocDao;
import dao.MauSacDao;
import dao.NhanVienDao;
import dao.SanPhamCTDao;
import dao.SanPhamDao;
import entity.BanHang;
import entity.ChatLieu;
import entity.ChiTietHoaDon;
import entity.ChiTietSanPham;
import entity.DanhSachSp;
import entity.DotGiamGia;
import entity.HoaDon;
import entity.HoaDon2;
import ui.ChonKhachHang;
import entity.HoaDonCho;
import entity.KichThuoc;
import entity.MauSac;
import entity.SanPham;
import java.sql.Timestamp;
import java.text.NumberFormat;
//import java.sql.Timestamp;
//import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import entity.KhachHang;
import entity.KhuyenMai;
import entity.Session;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import unti.XJdbc;
import unti.XQuery;

/**
 *
 * @author Admin
 */
public class BanHangView extends javax.swing.JInternalFrame {

    /**
     * Creates new form HoaDonView
     */
    private DotGiamGia_Ipml repodgg = new DotGiamGia_Ipml();
    private DotGGHoaDonDAO dotGGHoaDonDao = new DotGGHoaDonDAOIpml();
    DanhSachSpDao daoSach = new DanhSachSpDao();
    List<DanhSachSp> lstSach = new ArrayList<>();
    ChatLieuDao daoLieu = new ChatLieuDao();
    List<ChatLieu> lstLieu = new ArrayList<>();
    SanPhamDao daoPham = new SanPhamDao();
    List<SanPham> lstPham = new ArrayList<>();
    MauSacDao daoSac = new MauSacDao();
    List<MauSac> lstSac = new ArrayList<>();
    KichThuocDao daoThuoc = new KichThuocDao();
    List<KichThuoc> lstThuoc = new ArrayList<>();
    HoaDonChoDao daoCho = new HoaDonChoDao();
    List<HoaDonCho> lstCho = new ArrayList<>();

    List<BanHang> lsBanHang = new ArrayList<>();
    BanHangDao banHangDao = new BanHangDao();

    List<HoaDon> lsHoaDon = new ArrayList<>();
    HoaDonDao hoaDonDao = new HoaDonDao();

    HoaDon2Dao daoTiet = new HoaDon2Dao();
    List<HoaDon2> lstTiet = new ArrayList<>();

//    List<KhuyenMai> lsKhuyenMai = new ArrayList<>();
//    KhuyenMaiDao khuyenMaiDao = new KhuyenMaiDao();
    private KhachHangDao khachHangDao = new KhachHangDao();
    private NhanVienDao nhanVienDao = new NhanVienDao();
    private ChiTietHoaDonDao chiTietHoaDonDao = new ChiTietHoaDonDao();
    private SanPhamCTDao sanPhamCTDao = new SanPhamCTDao();

    private KhuyenMaiDao khuyenMaiDAO = new KhuyenMaiDao();
    private List<KhuyenMai> danhSachKhuyenMai = new ArrayList<>();

    private BigDecimal tongTienRaw = BigDecimal.ZERO;

    public BanHangView() {

        initComponents();
        fillToTableDanhSachSP();
        // fillKhuyenMaiToComboBox();
        loadKhuyenMaiToComboBox();
        fillToTableDanhSachSP();
        fillHoaDon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnChonKhachHang = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboKhuyenMai = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        btnTao = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        btnHuyDon = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_maDotBanHang = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachSp = new javax.swing.JTable();
        btnChonSanPham = new javax.swing.JButton();
        btnTimKiemSam = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        btnXoaSanPham = new javax.swing.JButton();
        btnXoaTatCa = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnChonKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tick.png"))); // NOI18N
        btnChonKhachHang.setText("Chọn Khách Hàng");
        btnChonKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChonKhachHang)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChonKhachHang)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sản phẩm"));

        jLabel4.setText("Mã hóa đơn:");

        jLabel5.setText("Tổng tiền:");

        jLabel6.setText("Khuyến mại:");

        cboKhuyenMai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhuyenMaiActionPerformed(evt);
            }
        });

        jLabel8.setText("Thành tiền:");

        btnTao.setText("Tạo");
        btnTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoActionPerformed(evt);
            }
        });

        jLabel7.setText("Giảm giá:");

        btnHuyDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        btnHuyDon.setText("Hủy đơn");
        btnHuyDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyDonActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel9.setText("Đợt giảm giá:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnHuyDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLamMoi)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTao))
                                    .addComponent(txtTongTien)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_maDotBanHang))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txtThanhTien))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_maDotBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuyDon)
                    .addComponent(btnLamMoi))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Accept.png"))); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThanhToan)
                .addGap(83, 83, 83))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThanhToan)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách hàng"));

        jLabel1.setText("Mã khách hàng:");

        jLabel2.setText("Tên khách hàng:");

        jLabel3.setText("Số điện thoại:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenKhachHang)
                    .addComponent(txtMaKhachHang)
                    .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        tblDanhSachSp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã CTSP", "Tên sản phẩm", "Giá", "Chất liệu", "Màu sắc", "Kích thước", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSachSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachSpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachSp);

        btnChonSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Create.png"))); // NOI18N
        btnChonSanPham.setText("Chọn sản phẩm");
        btnChonSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonSanPhamActionPerformed(evt);
            }
        });

        btnTimKiemSam.setText("Tìm kiếm sản phẩm");
        btnTimKiemSam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemSamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTimKiemSam, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(btnChonSanPham)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChonSanPham)
                    .addComponent(btnTimKiemSam)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hoá Đơn Chờ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Tổng tiền", "Tên khách hàng", "Tên nhân viên", "Ngày tạo", "Trạng thái"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHoaDon);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MaSanPham", "TenSanPham", "SoLuong", "DonGia"
            }
        ));
        jScrollPane3.setViewportView(tblGioHang);

        btnXoaSanPham.setText("Xoá sản phẩm");
        btnXoaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSanPhamActionPerformed(evt);
            }
        });

        btnXoaTatCa.setText("Xoá tất cả");
        btnXoaTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTatCaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnXoaTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnChonSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonSanPhamActionPerformed
        // TODO add your handling code here:
        // Lấy dòng được chọn
        int selectedRow = tblDanhSachSp.getSelectedRow();
        if (selectedRow < 0 || selectedRow >= lstSach.size()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sản phẩm trong bảng!");
            return;
        }

        DanhSachSp selectedSp = lstSach.get(selectedRow);
        String maSanPham = selectedSp.getMaSanPham();

        // Nhập số lượng
        String input = JOptionPane.showInputDialog(this, "Nhập số lượng muốn mua:");
        if (input == null) {
            return; // Cancel
        }
        int soLuongMua;
        try {
            soLuongMua = Integer.parseInt(input.trim());
            if (soLuongMua <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0!");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ!");
            return;
        }

        // Kiểm tra tồn kho
        int soLuongHienTai = selectedSp.getSoLuong();
        if (soLuongMua > soLuongHienTai) {
            JOptionPane.showMessageDialog(this, "Số lượng vượt quá tồn kho!");
            return;
        }

        // Trừ tồn kho
        selectedSp.setSoLuong(soLuongHienTai - soLuongMua);

        // Kiểm tra giỏ hàng
        boolean daCoTrongGioHang = false;
        for (BanHang spGH : lsBanHang) {
            if (spGH.getMaSanPham().equals(maSanPham)) {
                spGH.setSoLuong(spGH.getSoLuong() + soLuongMua);
                daCoTrongGioHang = true;
                break;
            }
        }

        if (!daCoTrongGioHang) {
            List<BanHang> banHangList = banHangDao.getById(maSanPham);
            if (!banHangList.isEmpty()) {
                BanHang spMoi = banHangList.get(0);
                spMoi.setSoLuong(soLuongMua);
                lsBanHang.add(spMoi);
            }
        }

        // Cập nhật bảng giỏ hàng
        fillToTableGioHang();

        // Cập nhật bảng Danh Sách Sản Phẩm (cột "Số lượng")
        DefaultTableModel dsSpModel = (DefaultTableModel) tblDanhSachSp.getModel();
        int colIndex = tblDanhSachSp.getColumnModel().getColumnIndex("Số lượng");
        if (colIndex >= 0 && colIndex < dsSpModel.getColumnCount()) {
            dsSpModel.setValueAt(selectedSp.getSoLuong(), selectedRow, colIndex);
        }

        // Cập nhật tổng tiền và form
        updateTongTien();
        setForm(soLuongMua);

    }//GEN-LAST:event_btnChonSanPhamActionPerformed

    private void btnChonKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonKhachHangActionPerformed
        // TODO add your handling code here:
        ChonKhachHang dialog = new ChonKhachHang(null, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // Sau khi dialog đóng lại, lấy thông tin khách hàng đã chọn
        KhachHang kh = dialog.selectedKhachHang;
        if (kh != null) {
            txtMaKhachHang.setText(kh.getMaKhachHang());
            txtTenKhachHang.setText(kh.getTenKhachHang());
            txtSDT.setText(kh.getSoDienThoai());
        }

    }//GEN-LAST:event_btnChonKhachHangActionPerformed

    private void btnTimKiemSamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemSamActionPerformed
        // TODO add your handling code here:
        timKiemSanPham();
    }//GEN-LAST:event_btnTimKiemSamActionPerformed

    private void btnXoaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSanPhamActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblGioHang.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm trong giỏ hàng để xoá!");
            return;
        }

        String maSanPham = tblGioHang.getValueAt(selectedRow, 0).toString();
        int soLuongTrongGio = Integer.parseInt(tblGioHang.getValueAt(selectedRow, 2).toString());

        // Nhập số lượng muốn xóa
        String input = JOptionPane.showInputDialog(this,
                "Nhập số lượng muốn xóa (tối đa " + soLuongTrongGio + "):");
        if (input == null) {
            return; // Người dùng bấm Cancel
        }
        int soLuongXoa;
        try {
            soLuongXoa = Integer.parseInt(input.trim());
            if (soLuongXoa <= 0 || soLuongXoa > soLuongTrongGio) {
                JOptionPane.showMessageDialog(this, "Số lượng xóa không hợp lệ!");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ!");
            return;
        }

        // Cập nhật số lượng trong giỏ hàng
        for (BanHang sp : lsBanHang) {
            if (sp.getMaSanPham().equals(maSanPham)) {
                if (soLuongXoa == soLuongTrongGio) {
                    // Xóa hẳn sản phẩm
                    lsBanHang.remove(sp);
                } else {
                    // Giảm số lượng
                    sp.setSoLuong(sp.getSoLuong() - soLuongXoa);
                }
                break;
            }
        }

        // Cập nhật lại số lượng trong danh sách sản phẩm
        for (DanhSachSp sp : lstSach) {
            if (sp.getMaSanPham().equals(maSanPham)) {
                sp.setSoLuong(sp.getSoLuong() + soLuongXoa);
                break;
            }
        }

        // Cập nhật lại bảng
        fillToTableDanhSachSP();
        updateGioHangTable();
        updateTongTien();
        JOptionPane.showMessageDialog(this, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnXoaSanPhamActionPerformed

    private void btnXoaTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTatCaActionPerformed
        // TODO add your handling code here:
        if (lsBanHang.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Giỏ hàng đang trống!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xoá toàn bộ giỏ hàng?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Trả lại số lượng cho danh sách sản phẩm
        for (BanHang bh : lsBanHang) {
            for (DanhSachSp sp : lstSach) {
                if (sp.getMaSanPham().equals(bh.getMaSanPham())) {
                    sp.setSoLuong(sp.getSoLuong() + bh.getSoLuong());
                    break;
                }
            }
        }

        // Xoá toàn bộ giỏ hàng
        lsBanHang.clear();

        // Cập nhật bảng
        fillToTableDanhSachSP();
        updateGioHangTable();
        JOptionPane.showMessageDialog(this, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnXoaTatCaActionPerformed

    //  private HoaDonDao hoaDonDao = new HoaDonDao();
    private DotGiamGia dotGiamGiaHienTai;

    private void btnTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoActionPerformed
        try {
            // 1) Tạo mã hóa đơn
            String maHD = hoaDonDao.getNewMaHoaDon();
            txtMaHoaDon.setText(maHD);

            // 2) Lấy hoặc tạo khách hàng
            String tenKH = txtTenKhachHang.getText().trim();
            String maKH;

            if (tenKH.isEmpty()) {
                // KH bán lẻ
                maKH = "KHBL";
                KhachHang khBL = khachHangDao.findByMa(maKH);

                if (khBL == null) {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy KHBL!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                txtMaKhachHang.setText(khBL.getMaKhachHang());
                txtTenKhachHang.setText(khBL.getTenKhachHang());
                txtSDT.setText(khBL.getSoDienThoai());
            } else {
                // KH mới
                maKH = khachHangDao.getNewMaKhachHang();

                KhachHang kh = new KhachHang();
                kh.setMaKhachHang(maKH);
                kh.setTenKhachHang(tenKH);
                kh.setSoDienThoai(txtSDT.getText().trim());

                khachHangDao.insert(kh);
                txtMaKhachHang.setText(maKH);
            }

            // 3) Tạo hóa đơn
            HoaDon hd = new HoaDon();
            hd.setMaHoaDon(maHD);
            hd.setMaNhanVien(Session.MaNhanVien);
            hd.setMaKhachHang(maKH);
            hd.setNgayTao(new java.sql.Date(System.currentTimeMillis()));
            hd.setTrangThai(false);

            if (!hoaDonDao.add(hd)) {
                JOptionPane.showMessageDialog(this, "Tạo hóa đơn thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // ------------------------------------------------------
            // 4) TÌM ĐỢT GIẢM GIÁ ĐANG HOẠT ĐỘNG LỚN NHẤT
            // ------------------------------------------------------
            apDungDotGiamGiaChoHoaDon(maHD);

            // 5) Load lại hóa đơn
            fillHoaDon();
            JOptionPane.showMessageDialog(this, "Tạo hóa đơn thành công!");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTaoActionPerformed

    // Hàm áp dụng đợt giảm giá cho hóa đơn
    private void apDungDotGiamGiaChoHoaDon(String maHD) {

        // Lấy đợt giảm giá hiện tại từ repository
        dotGiamGiaHienTai = repodgg.getDotGiamGiaHienTai();

        if (dotGiamGiaHienTai != null) {
            // Gán lên giao diện
            txt_maDotBanHang.setText(dotGiamGiaHienTai.getMaDotGG());

            // Lưu vào bảng trung gian DotGG_HoaDon
            // CẢNH BÁO: insert phải kiểm tra trùng khóa nếu bảng này dùng PK kép
            dotGGHoaDonDao.insert(maHD, dotGiamGiaHienTai.getMaDotGG());

        } else {
            // Không có đợt giảm giá
            txt_maDotBanHang.setText("");
        }
    }

    private void clearForm() {
        txtMaHoaDon.setText("");
        txtTenKhachHang.setText("");
        txtMaKhachHang.setText("");
        txtSDT.setText("");
        txtTongTien.setText("");
        cboKhuyenMai.removeAllItems();
        txtGiamGia.setText("");
        txtThanhTien.setText("");
        JOptionPane.showMessageDialog(this, "Làm mới thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }


    private void tblDanhSachSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachSpMouseClicked
        // TODO add your handling code here:
        int intdexRow = tblDanhSachSp.getSelectedRow();

        fillToTableGioHang();
    }//GEN-LAST:event_tblDanhSachSpMouseClicked

    private void btnHuyDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyDonActionPerformed
        // TODO add your handling code here:
        String maHD = txtMaHoaDon.getText().trim();

        if (maHD.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn để hủy!");
            return;
        }

        try {
            // 1) Không cho hủy hóa đơn đã thanh toán
            if (hoaDonDao.isDaThanhToan(maHD)) {
                JOptionPane.showMessageDialog(this, "Hóa đơn đã thanh toán! Không thể hủy.");
                return;
            }

            // 2) Không cho hủy nếu có sản phẩm
            if (!hoaDonDao.hoaDonChuaCoSanPham(maHD)) {
                JOptionPane.showMessageDialog(this, "Hóa đơn đã có sản phẩm → không thể hủy!");
                return;
            }

            // 3) Xóa hóa đơn + bảng con
            if (hoaDonDao.deleteHoaDon(maHD)) {
                JOptionPane.showMessageDialog(this, "Hủy hóa đơn thành công!");
                clearForm();
                fillHoaDon();
                loadKhuyenMaiToComboBox();
            } else {
                JOptionPane.showMessageDialog(this, "Hủy hóa đơn thất bại!");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi hủy hóa đơn!");
        }
    }//GEN-LAST:event_btnHuyDonActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
        loadKhuyenMaiToComboBox();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void cboKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhuyenMaiActionPerformed
        try {
            // 0) Tổng tiền
            String tongTienStr = txtTongTien.getText().replace(",", "").trim();
            if (tongTienStr.isEmpty()) {
                txtThanhTien.setText("0");
                txtGiamGia.setText("0");
                return;
            }
            double tongTien = Double.parseDouble(tongTienStr);

            // 1) Giảm đợt (tính chuẩn bằng BigDecimal khi cần)
            double giamDot = 0.0;
            if (dotGiamGiaHienTai != null) {
                // Chuẩn hóa kiểu LoaiGiamGia: dùng giá trị lưu trong DB, VD: "PhanTram" hoặc "TienMat"
                String loaiDot = dotGiamGiaHienTai.getLoaiGiamGia().trim();
                double giaTriDot = dotGiamGiaHienTai.getGiaTri().doubleValue();

                if (loaiDot.equalsIgnoreCase("PhanTram") || loaiDot.equals("%")) {
                    giamDot = tongTien * giaTriDot / 100.0;
                } else {
                    // Tiền mặt
                    giamDot = giaTriDot;
                }
            }

            double tienSauDot = Math.max(0, tongTien - giamDot);

            // 2) Giảm phiếu (lưu ý: KHÔNG reload danh sách trong event)
            double giamPhieu = 0.0;
            int index = cboKhuyenMai.getSelectedIndex(); // index 0 = "Không áp dụng"
            if (index > 0) {
                KhuyenMai km = danhSachKhuyenMai.get(index - 1);
                String loaiPhieu = km.getTenHinhThucGG() == null ? km.getTenHinhThucGG().trim() : km.getTenHinhThucGG().trim();
                double giaTri = km.getGiaTri();

                if (loaiPhieu.equalsIgnoreCase("Giảm theo phầm trăm") || loaiPhieu.equals("%")) {
                    giamPhieu = tienSauDot * giaTri / 100.0;
                } else {
                    giamPhieu = giaTri;
                }
            } else {
                giamPhieu = 0.0; // khi chọn "Không áp dụng" -> reset
            }

            // 3) Kết quả
            double tongGiam = giamDot + giamPhieu;
            double thanhTien = Math.max(0, tienSauDot - giamPhieu);

            txtGiamGia.setText(String.format("%,.0f", tongGiam));
            txtThanhTien.setText(String.format("%,.0f", thanhTien));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi tính giảm giá!");
            txtThanhTien.setText("0");
            txtGiamGia.setText("0");
        }

    }//GEN-LAST:event_cboKhuyenMaiActionPerformed


    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        // 1. Lấy mã hóa đơn
        String maHD = txtMaHoaDon.getText().trim();

        if (maHD.isBlank()) {
            JOptionPane.showMessageDialog(this, "Mã hóa đơn không được để trống!");
            return;
        }

        // 2. Kiểm tra giỏ hàng có sản phẩm chưa
        DefaultTableModel model = (DefaultTableModel) tblGioHang.getModel();
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Giỏ hàng đang trống!");
            return;
        }

        // 3. Lưu chi tiết hóa đơn
        for (int i = 0; i < model.getRowCount(); i++) {
            String maSP = model.getValueAt(i, 0).toString();
            String maCTSP = sanPhamCTDao.getMaChiTietSPByMaSP(maSP);

            if (maCTSP == null) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy mã chi tiết sản phẩm cho " + maSP);
                continue;
            }

            try {
                ChiTietHoaDon cthd = new ChiTietHoaDon();
                cthd.setMaChiTietHoaDon("CTHD" + System.currentTimeMillis() + i);
                cthd.setMaHoaDon(maHD);
                cthd.setMaChiTietSP(maCTSP);
                cthd.setSoLuong(Integer.parseInt(model.getValueAt(i, 2).toString()));

                String donGiaStr = model.getValueAt(i, 3).toString().replace(",", "");
                cthd.setDonGia(new BigDecimal(donGiaStr));

                chiTietHoaDonDao.insert(cthd);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi số lượng hoặc đơn giá tại dòng " + (i + 1));
                return;
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi lưu chi tiết hóa đơn tại dòng " + (i + 1));
                return;
            }
        }

        // 4. Kiểm tra tổng tiền và thành tiền
        if (txtTongTien.getText().isBlank() || txtThanhTien.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra lại Tổng tiền và Thành tiền!");
            return;
        }

        // 5. Cập nhật tổng tiền, tiền giảm, tiền sau giảm
        try {
            double tongTien = Double.parseDouble(txtTongTien.getText().replace(",", ""));
            double thanhTien = Double.parseDouble(txtThanhTien.getText().replace(",", ""));
            double tienGiam = tongTien - thanhTien;

            String sql = "UPDATE HoaDon SET TongTien = ?, giatri = ?, TienSauGiam = ? WHERE MaHoaDon = ?";
            int rowsAffected = XJdbc.executeUpdate(sql, tongTien, tienGiam, thanhTien, maHD);

            if (rowsAffected <= 0) {
                JOptionPane.showMessageDialog(this, "Không cập nhật được thông tin hóa đơn!");
                return;
            }

            // 6. Cập nhật trạng thái hóa đơn thành đã thanh toán (true)
            boolean daCapNhatTrangThai = hoaDonDao.updateTrangThai(maHD, true);

            if (!daCapNhatTrangThai) {
                JOptionPane.showMessageDialog(this, "Cập nhật trạng thái hóa đơn thất bại!");
                return;
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi định dạng số tiền. Vui lòng kiểm tra lại!");
            return;
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật thông tin hóa đơn!");
            return;
        }

        // 7. Thông báo & Làm mới
        JOptionPane.showMessageDialog(this, "Thanh toán thành công!");
        // 8. sét txt_maDotBanHang.setText(""); 
        txt_maDotBanHang.setText("");
        clearForm();   // Làm mới form (nếu có)
        fillHoaDon();  // Load lại danh sách hóa đơn
        loadKhuyenMaiToComboBox();
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        int row = tblHoaDon.getSelectedRow();
        if (row >= 0) {
            String maHD = tblHoaDon.getValueAt(row, 0).toString(); // Cột 0 là mã hóa đơn
            txtMaHoaDon.setText(maHD);
        }
    }//GEN-LAST:event_tblHoaDonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonKhachHang;
    private javax.swing.JButton btnChonSanPham;
    private javax.swing.JButton btnHuyDon;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTao;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnTimKiemSam;
    private javax.swing.JButton btnXoaSanPham;
    private javax.swing.JButton btnXoaTatCa;
    private javax.swing.JComboBox<String> cboKhuyenMai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblDanhSachSp;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txt_maDotBanHang;
    // End of variables declaration//GEN-END:variables

    private void fillToTableDanhSachSP() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachSp.getModel();
        model.setRowCount(0);
        NumberFormat currencyFormat = NumberFormat.getInstance();
        lstSach = daoSach.getAll();

        for (DanhSachSp sp : lstSach) {
            SanPham sanPham = daoPham.findById(sp.getMaSanPham());
            ChatLieu chatLieu = daoLieu.finById(sp.getMaChatLieu());
            MauSac mauSac = daoSac.findById(sp.getMaMauSac());
            KichThuoc kichThuoc = daoThuoc.findById(sp.getMaKichThuoc());

            if (sanPham == null || mauSac == null || kichThuoc == null) {
                System.out.println("Dữ liệu bị thiếu với mã sản phẩm: " + sp.getMaChiTietSP());
                continue; // Bỏ qua dòng này nếu thiếu dữ liệu
            }

            Object[] data = {
                sp.getMaChiTietSP(),
                sanPham.getTenSanPham(),
                currencyFormat.format(sp.getGia()),
                chatLieu.getChatLieu(),
                mauSac.getTenMau(),
                kichThuoc.getKichThuoc(),
                sp.getSoLuong()
            };
            model.addRow(data);
        }
    }

    private void fillToTableGioHang() {
        // Cập nhật giỏ hàng
        DefaultTableModel gioHangModel = (DefaultTableModel) tblGioHang.getModel();
        gioHangModel.setRowCount(0);

        NumberFormat currencyFormat = NumberFormat.getInstance(); // định dạng số

        for (BanHang bh : lsBanHang) {
            // Lấy giá và số lượng, giả sử bh.getGia() trả về BigDecimal
            BigDecimal gia = bh.getGia() != null ? bh.getGia() : BigDecimal.ZERO;
            int soLuong = bh.getSoLuong();

            BigDecimal tongGia = gia.multiply(BigDecimal.valueOf(soLuong));

            // Định dạng hiển thị tiền (ví dụ 1,000,000)
            String giaHienThi = currencyFormat.format(tongGia);

            Object[] rowData = {
                bh.getMaSanPham(),
                bh.getTenSanPham(),
                soLuong,
                giaHienThi
            };
            gioHangModel.addRow(rowData);
        }
    }

    private void loadKhuyenMaiToComboBox() {
        danhSachKhuyenMai = khuyenMaiDAO.getAllActive(); // Lưu danh sách lại

        cboKhuyenMai.removeAllItems();
        cboKhuyenMai.addItem("Không áp dụng");
        for (KhuyenMai km : danhSachKhuyenMai) {
            cboKhuyenMai.addItem(km.getMaPhieu()); // Hiển thị chuỗi mô tả
        }
    }

    private void updateGioHangTable() {
        DefaultTableModel model = (DefaultTableModel) tblGioHang.getModel();
        model.setRowCount(0);
        NumberFormat currencyFormat = NumberFormat.getInstance();

        for (BanHang bh : lsBanHang) {
            BigDecimal gia = bh.getGia() != null ? bh.getGia() : BigDecimal.ZERO;
            int soLuong = bh.getSoLuong();

            BigDecimal thanhTien = gia.multiply(BigDecimal.valueOf(soLuong));

            model.addRow(new Object[]{
                bh.getMaSanPham(),
                bh.getTenSanPham(),
                soLuong,
                currencyFormat.format(thanhTien.doubleValue())
            });
        }
    }

    private void timKiemSanPham() {
        String tuKhoa = txtTimKiem.getText().trim();
        if (tuKhoa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã hoặc tên sản phẩm để tìm kiếm!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblDanhSachSp.getModel();
        model.setRowCount(0);

        // Ưu tiên tìm theo mã (chính xác trước)
        DanhSachSp danhSp = daoSach.findById(tuKhoa);
        if (danhSp != null) {
            Object[] data = {
                danhSp.getMaChiTietSP(),
                daoPham.findById(danhSp.getMaSanPham()).getTenSanPham(),
                danhSp.getGia(),
                daoLieu.finById(danhSp.getMaChatLieu()).getChatLieu(),
                daoSac.findById(danhSp.getMaMauSac()).getTenMau(),
                daoThuoc.findById(danhSp.getMaKichThuoc()).getKichThuoc(),
                danhSp.getSoLuong()
            };
            model.addRow(data);
        } else {
            // Nếu không tìm thấy theo mã, tìm theo tên (danh sách nhiều kết quả)
            List<DanhSachSp> danhSachTimDuoc = daoSach.findByTenSanPham(tuKhoa); // Tạo hàm này trong DAO

            if (danhSachTimDuoc.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm có tên hoặc mã: " + tuKhoa);
            } else {
                for (DanhSachSp sp : danhSachTimDuoc) {
                    Object[] data = {
                        sp.getMaChiTietSP(),
                        daoPham.findById(sp.getMaSanPham()).getTenSanPham(),
                        sp.getGia(),
                        daoLieu.finById(sp.getMaChatLieu()).getChatLieu(),
                        daoSac.findById(sp.getMaMauSac()).getTenMau(),
                        daoThuoc.findById(sp.getMaKichThuoc()).getKichThuoc(),
                        sp.getSoLuong()
                    };
                    model.addRow(data);
                }
            }
        }
    }

    private void loadHoaDon() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0); // clear bảng

        List<HoaDonCho> list = daoCho.getAll(); // lấy toàn bộ hóa đơn
        for (HoaDonCho hd : list) {
            if (!hd.isTrangThaiKH()) { // chỉ lấy hóa đơn đang tạo (chưa thanh toán)
                model.addRow(new Object[]{
                    hd.getMaHoaDon(),
                    khachHangDao.findById(hd.getMaKhachHang()).getTenKhachHang(),
                    hd.getTenNhanVien(), // hoặc lấy tên nhân viên nếu có bảng NhanVien
                    hd.getNgayTao(),
                    hd.isTrangThaiKH() ? "Đã thanh toán" : "Chờ thanh toán"
                });
            }
        }
    }

    private void fillHoaDon() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0);
        List<HoaDon2> lstHoaDon = daoTiet.getAll();  // trạng thais chưa thanh toán

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (HoaDon2 ct : lstHoaDon) {
            Object[] data = {
                ct.getMaHoaDon(),
                ct.getTongTien() != null ? ct.getTongTien().toString() : "", // Nếu muốn hiển thị tổng tiền
                ct.getTenKhachHang(),
                ct.getHoTen(),
                ct.getNgayTao() != null ? sdf.format(ct.getNgayTao()) : "",
                ct.isTrangThai() ? "Đã Thanh Toán" : "Chưa Thanh Toán", // ct.getMaNhanVien(),
            // ct.getTenNhanVien(),
            // ct.getMaKhachHang(),
            };
            model.addRow(data);
        }
    }

    private void setFormm(int soLuongMua) {
        int selectedRow = tblDanhSachSp.getSelectedRow();
        if (selectedRow != -1) {
            try {
                double gia = Double.parseDouble(tblDanhSachSp.getValueAt(selectedRow, 2).toString());
                double tongTien = gia * soLuongMua;

                txtTongTien.setText(String.valueOf(tongTien));

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Lỗi đọc giá sản phẩm!");
            }
        }
    }

    private void updateTongTien() {
        tongTienRaw = BigDecimal.ZERO;

        for (BanHang sp : lsBanHang) {
            BigDecimal gia = sp.getGia() != null ? sp.getGia() : BigDecimal.ZERO;
            int soLuong = sp.getSoLuong();

            tongTienRaw = tongTienRaw.add(gia.multiply(BigDecimal.valueOf(soLuong)));
        }

        txtTongTien.setText(String.format("%,.0f", tongTienRaw));
    }

    private void setForm(int soLuongMua) {
        int selectedRow = tblDanhSachSp.getSelectedRow();
        if (selectedRow != -1) {
            try {
                String giaGocStr = tblDanhSachSp.getValueAt(selectedRow, 2).toString().replace(",", "");
                String giaSauGiamStr = tblDanhSachSp.getValueAt(selectedRow, 3).toString().replace(",", "");

                BigDecimal giaGoc = new BigDecimal(giaGocStr);
                BigDecimal giaSauGiam = new BigDecimal(giaSauGiamStr);

                BigDecimal tongTien = giaSauGiam.multiply(BigDecimal.valueOf(soLuongMua));
                BigDecimal khuyenMai = giaGoc.subtract(giaSauGiam).multiply(BigDecimal.valueOf(soLuongMua));

                txtThanhTien.setText(String.format("%,.0f", tongTien));
                // txtKhuyenMai.setText(String.format("%,.0f", khuyenMai));

            } catch (NumberFormatException e) {
                //JOptionPane.showMessageDialog(this, "Lỗi đọc hoặc chuyển đổi giá sản phẩm!");
            }
        }
    }

}
