package ui;

import dao.ChatLieuDao;
import dao.HoaDon2Dao;
import dao.HoaDonChiTietDao;
import dao.KichThuocDao;
import dao.MauSacDao;
import dao.SanPhamDao;
import dao.XuatXuDao;
import entity.HoaDon;
import entity.HoaDon2;
import entity.HoaDonChiTiet;
import entity.SanPham;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
//import org.apache.poi.ss.usermodel.*;      
//import org.apache.poi.xssf.usermodel.XSSFWorkbook; 
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JTable;
import java.io.File;
import javax.swing.table.TableModel;
//import org.apache.poi.xssf.usermodel.XSSFRow;
//import org.apache.poi.xssf.usermodel.XSSFSheet;
//import com.itextpdf.text.*;
//import com.itextpdf.text.pdf.*;
import javax.swing.table.DefaultTableModel;
import java.io.FileOutputStream;
//import com.itextpdf.text.Document;
//import com.itextpdf.text.DocumentException;
//import com.itextpdf.text.Paragraph;
//import com.itextpdf.text.Font;
//import com.itextpdf.text.Font.FontFamily;


/**
 *
 * @author Admin
 */
public class LichSuView extends javax.swing.JInternalFrame {

    HoaDon2Dao daoTiet = new HoaDon2Dao();
    List<HoaDon2> lstTiet = new ArrayList<>();
    HoaDonChiTietDao daoDon = new HoaDonChiTietDao();
    List<HoaDonChiTiet> lstDon = new ArrayList<>();
    SanPhamDao daoPham = new SanPhamDao();
    List<SanPham> lstPham = new ArrayList<>();
    MauSacDao daoSac = new MauSacDao();
    KichThuocDao daoThuoc = new KichThuocDao();
    ChatLieuDao daoLieu = new ChatLieuDao();
    XuatXuDao daoXu = new XuatXuDao();

    /**
     * Creates new form DoiMatKhauView
     */
    public LichSuView() {
        initComponents();
        fillToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDonChiTiet = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        txttim = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jdclich1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        cbotrangthai = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jdclich2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1003, 900));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hoá Đơn Chi Tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        tblHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hoá đơn", "Mã hoá đơn chi tiết", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Màu sắc", "Kích thước", "Chất liệu", "Nơi nhập", "Đơn giá"
            }
        ));
        jScrollPane2.setViewportView(tblHoaDonChiTiet);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hoá Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Mã hoá đơn", "Tổng tiền", "Số tiền được giảm", "Tổng tiền sau giảm", "Trạng thái", "Mã nhân viên", "Tên nhân viên", "Ngày tạo"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jdclich1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jdclich1MouseExited(evt);
            }
        });
        jdclich1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jdclich1InputMethodTextChanged(evt);
            }
        });
        jdclich1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdclich1PropertyChange(evt);
            }
        });

        jLabel2.setText("Trạng thái:");

        cbotrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đã thanh toán", "Chưa thanh toán", " " }));
        cbotrangthai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbotrangthaiItemStateChanged(evt);
            }
        });

        jLabel3.setText("Từ ngày:");

        btnIn.setText("In");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        jLabel1.setText("Đến ngày:");

        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbotrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdclich2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jdclich1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIn)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdclich1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTimKiem)
                            .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(cbotrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIn)
                            .addComponent(jButton1))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jdclich2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        TimKiemTongHop();

    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblHoaDon.getSelectedRow();
        if (selectedRow >= 0) {
            String maHD = tblHoaDon.getValueAt(selectedRow, 3).toString();
            fillChiTietHoaDon(maHD);
        }
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void cbotrangthaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbotrangthaiItemStateChanged
        // TODO add your handling code here:
        TimKiemTheoTrangThai();
    }//GEN-LAST:event_cbotrangthaiItemStateChanged

    private void jdclich1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jdclich1InputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jdclich1InputMethodTextChanged

    private void jdclich1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdclich1MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jdclich1MouseExited

    private void jdclich1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdclich1PropertyChange
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jdclich1PropertyChange

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
//        inHoaDonVaChiTietPDF(tblHoaDon, tblHoaDonChiTiet);
    }//GEN-LAST:event_btnInActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TimKiemTheoNgay();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbotrangthai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdclich1;
    private com.toedter.calendar.JDateChooser jdclich2;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblHoaDonChiTiet;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables

    private void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0);
        lstTiet = daoTiet.getAll_all();
        for (HoaDon2 ct : lstTiet) {
            Object[] data = {
                ct.getMaKhachHang(),
                ct.getTenKhachHang(),
                ct.getSoDienThoai(),
                ct.getMaHoaDon(),
                ct.getTongTien(),
                ct.getGiaTri(),
                ct.getTienSauGiam(),
                ct.isTrangThai() ? "Đã Thanh Toán" : "Chưa Thanh Toán",
                ct.getMaNhanVien(),
                ct.getHoTen(),
                ct.getNgayTao()
            };
            model.addRow(data);
        }
    }
    private void TimKiemTongHop() {
          String keyword = txttim.getText().trim();

    DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
    model.setRowCount(0);

    List<HoaDon2> danhSach;

    if (keyword.isEmpty()) {
        danhSach = daoTiet.getAll();
    } else {
        danhSach = daoTiet.findAllFields(keyword);

        if (danhSach.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy kết quả phù hợp!");
            return;
        }
    }
        for (HoaDon2 hd : danhSach) {
            Object[] data = {
           hd.getMaKhachHang(),
                hd.getTenKhachHang(),
                hd.getSoDienThoai(),
                hd.getMaHoaDon(),
                hd.getTongTien(),
                hd.getGiaTri(),
                hd.getTienSauGiam(),
                hd.isTrangThai() ? "Đã Thanh Toán" : "Chưa Thanh Toán",
                hd.getMaNhanVien(),
                hd.getHoTen(),
                hd.getNgayTao()
            };
            model.addRow(data);
        }
    }
    private void fillChiTietHoaDon(String maHD) {
        DefaultTableModel model = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        model.setRowCount(0);
        lstDon = (List<HoaDonChiTiet>) daoDon.findById(maHD);
        for (HoaDonChiTiet cthd : lstDon) {
            Object[] data={
                cthd.getMaHoaDon(),
                cthd.getMaChiTietHoaDon(),
                cthd.getMaSanPham(),
                daoPham.findById(cthd.getMaSanPham()).getTenSanPham(),
                cthd.getSoLuong(),
                daoSac.findById(cthd.getMaMauSac()).getTenMau(),
                daoThuoc.findById(cthd.getMaKichThuoc()).getKichThuoc(),
                daoLieu.finById(cthd.getMaChatLieu()).getChatLieu(),
                daoXu.findxuatXu(cthd.getMaXuatSu()).getNoiNhap(),
                cthd.getDonGia()
            };
            model.addRow(data);
        }
    }
     private void TimKiemTheoTrangThai(){
    String chon = cbotrangthai.getSelectedItem().toString();
    DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
    model.setRowCount(0);
    if (chon.equals("Tất cả")) {
        lstTiet = daoTiet.getAll();
    } else {
        boolean TrangThai = chon.equals("Đã thanh toán");
        lstTiet = daoTiet.findTrangThai(TrangThai);
    }
    for (HoaDon2 hd : lstTiet) {
            Object[] data={
                hd.getMaKhachHang(),
                hd.getTenKhachHang(),
                hd.getSoDienThoai(),
                hd.getMaHoaDon(),
                hd.getTongTien(),
                hd.getGiaTri(),
                hd.getTienSauGiam(),
                hd.isTrangThai() ? "Đã Thanh Toán" : "Chưa Thanh Toán",
                hd.getMaNhanVien(),
                hd.getHoTen(),
                hd.getNgayTao()
            };
            model.addRow(data);
        }
    
    }
   private void TimKiemTheoNgay() {
    Date tuNgay = jdclich1.getDate();
    Date denNgay = jdclich2.getDate();

    DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
    model.setRowCount(0);

    if (tuNgay == null || denNgay == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn cả Từ ngày và Đến ngày!");
        return;
    }

    java.sql.Date sqlTuNgay = new java.sql.Date(tuNgay.getTime());
    java.sql.Date sqlDenNgay = new java.sql.Date(denNgay.getTime());

    lstTiet = daoTiet.findNgayTaoKhoang(sqlTuNgay, sqlDenNgay);

    if (lstTiet == null || lstTiet.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn nào trong khoảng thời gian này!");
        return;
    }

    for (HoaDon2 hd : lstTiet) {
        Object[] data = {
            hd.getMaKhachHang(),
            hd.getTenKhachHang(),
            hd.getSoDienThoai(),
            hd.getMaHoaDon(),
            hd.getTongTien(),
            hd.getGiaTri(),
            hd.getTienSauGiam(),
            hd.isTrangThai() ? "Đã Thanh Toán" : "Chưa Thanh Toán",
            hd.getMaNhanVien(),
            hd.getHoTen(),
            hd.getNgayTao()
        };
        model.addRow(data);
    }
}


//private void inHoaDonVaChiTietPDF(JTable tblHoaDon, JTable tblHoaDonChiTiet) {
//    int selectedRow = tblHoaDon.getSelectedRow();
//    if (selectedRow == -1) {
//        JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 hóa đơn trước khi in!");
//        return;
//    }
//    String maHD = String.valueOf(tblHoaDon.getValueAt(selectedRow, 3));
//    String filePath = "D:/Exported/hoadon_" + maHD + ".pdf";
//
//    Document document = new Document(); 
//    try {
//        PdfWriter.getInstance(document, new FileOutputStream(filePath));
//        document.open();
//
//        BaseFont bf = BaseFont.createFont("C:/Windows/Fonts/arial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
//        Font titleFont = new Font(bf, 16, Font.BOLD);
//        Font headerFont = new Font(bf, 12, Font.BOLD);
//        Font normalFont = new Font(bf, 12, Font.NORMAL);
//
//        Paragraph title = new Paragraph("HÓA ĐƠN BÁN HÀNG", titleFont);
//        title.setAlignment(Element.ALIGN_CENTER);
//        document.add(title);
//        document.add(new Paragraph(" "));
//
//        DefaultTableModel modelHD = (DefaultTableModel) tblHoaDon.getModel();
//        PdfPTable tblInfo = new PdfPTable(2);
//        tblInfo.setWidthPercentage(100);
//        tblInfo.setSpacingBefore(6f);
//        tblInfo.setSpacingAfter(6f);
//
//        for (int col = 0; col < modelHD.getColumnCount(); col++) {
//            String colName = modelHD.getColumnName(col);
//            Object value = modelHD.getValueAt(selectedRow, col);
//
//            PdfPCell cellLabel = new PdfPCell(new Paragraph(colName, headerFont));
//            cellLabel.setBorder(PdfPCell.NO_BORDER);
//            tblInfo.addCell(cellLabel);
//
//            PdfPCell cellVal = new PdfPCell(new Paragraph(value != null ? value.toString() : "", normalFont));
//            cellVal.setBorder(PdfPCell.NO_BORDER);
//            tblInfo.addCell(cellVal);
//        }
//        document.add(tblInfo);
//        document.add(new Paragraph(" "));
//
//
//        DefaultTableModel modelCT = (DefaultTableModel) tblHoaDonChiTiet.getModel();
//        if (modelCT.getRowCount() == 0) {
//            document.add(new Paragraph("Không có chi tiết hóa đơn.", normalFont));
//        } else {
//            document.add(new Paragraph("Chi tiết sản phẩm:", headerFont));
//            PdfPTable tblDetail = new PdfPTable(modelCT.getColumnCount());
//            tblDetail.setWidthPercentage(100);
//            tblDetail.setSpacingBefore(6f);
//
//   
//            for (int c = 0; c < modelCT.getColumnCount(); c++) {
//                PdfPCell h = new PdfPCell(new Paragraph(modelCT.getColumnName(c), headerFont));
//                h.setHorizontalAlignment(Element.ALIGN_CENTER);
//                tblDetail.addCell(h);
//            }
//
//
//            for (int r = 0; r < modelCT.getRowCount(); r++) {
//                for (int c = 0; c < modelCT.getColumnCount(); c++) {
//                    Object v = modelCT.getValueAt(r, c);
//                    PdfPCell cell = new PdfPCell(new Paragraph(v != null ? v.toString() : "", normalFont));
//                    tblDetail.addCell(cell);
//                }
//            }
//            document.add(tblDetail);
//        }
//
//        document.close();
//        JOptionPane.showMessageDialog(this, "In hoá đơn thành công");
//
//    } catch (DocumentException | IOException ex) {
//        ex.printStackTrace();
//        JOptionPane.showMessageDialog(this, "Không thể in hoá đơn");
//    } finally {
//        if (document.isOpen()) document.close();
//    }
//}

}
